#!/bin/bash
## Output to CSV format
echo "1.1.2, Ensure separate partition exists for /tmp (Scored), $result1_1_2" 
echo "1.1.5, Ensure noexec option set on /tmp partition (Scored), $result1_1_5"
echo "1.1.11, Ensure separate partition exists for /var/log (Scored), $result1_1_11"
echo "1.1.12, Ensure separate partition exists for /var/log/audit (Scored), $result1_1_12"
echo "1.1.13, Ensure separate partition exists for /home (Scored), $result1_1_13"
echo "1.1.14, Ensure nodev option set on /home partition (Scored), $result1_1_14"
echo "1.2.3, Ensure gpgcheck is globally activated (Scored), $result1_2_3" 
echo "1.3.1, Ensure AIDE is installed (Scored), $result1_3_1"
echo "1.3.2, Ensure filesystem integrity is regularly checked (Scored), $result1_3_2"
echo "1.4.1, Ensure permissions on bootloader config are configured (Scored), $result1_4_1"
echo "1.5.1, Ensure core dumps are restricted (Scored), $result1_5_1"
echo "1.5.3, Ensure address space layout randomization (ASLR) is enabled (Scored), $result1_5_3"
echo "1.6.1.1, Ensure SELinux is not disabled in bootloader configuration (Scored), $result1_6_1_1"
echo "1.6.1.2, Ensure the SELinux state is enforcing (Scored), $result1_6_1_2"
echo "1.6.1.4, Ensure SETroubleshoot is not installed (Scored), $result1_6_1_4"
echo "1.6.1.5, Ensure the MCS Translation Service (mcstrans) is not installed (Scored), $result1_6_1_5"
echo "1.6.1.6, Ensure no unconfined daemons exist (Scored), $result1_6_1_6"