#!/bin/bash

echo "4.1.1.1 Ensure audit log storage size is configured (Not Scored), $result4_1_1_1"
echo "4.1.1.2 Ensure system is disabled when audit logs are full (Scored), $result4_1_1_2"
echo "4.1.1.3 Ensure audit logs are not automatically deleted (Scored), $result4_1_1_3"
echo "4.1.2 Ensure auditd service is enabled (Scored), $result4_1_2"
echo "4.1.3 Ensure auditing for processes that start prior to auditd is enabled (Scored), $result4_1_3"
echo "4.1.4 Ensure events that modify date and time information are collected (Scored), $result4_1_4"
echo "4.1.5 Ensure events that modify user/group information are collected (Scored), $result4_1_5"
echo "4.1.6 Ensure events that modify the system's network environment are collected (Scored), $result4_1_6"
echo "4.1.7 Ensure events that modify the system's Mandatory Access Controls are collected (Scored), $result4_1_7"
echo "4.1.8 Ensure login and logout events are collected (Scored), $result4_1_8"
echo "4.1.9 Ensure session initiation information is collected (Scored), $result4_1_9"
echo "4.1.10 Ensure discretionary access control permission modification events are collected (Scored), $result4_1_10"
echo "4.1.11 Ensure unsuccessful unauthorized file access attempts are collected (Scored), $result4_1_11"
echo "4.1.13 Ensure successful file system mounts are collected (Scored), $result4_1_13"
echo "4.1.14 Ensure file deletion events by users are collected (Scored), $result4_1_14"
echo "4.1.15 Ensure changes to system administration scope (sudoers) is collected (Scored), $result4_1_15"
echo "4.1.16 Ensure system administrator actions (sudolog) are collected (Scored), $result4_1_16"
echo "4.1.17 Ensure kernel module loading and unloading is collected (Scored), $result4_1_17"
echo "4.1.18 Ensure the audit configuration is immutable (Scored), $result4_1_18"
echo "4.2.1.1 Ensure rsyslog Service is enabled (Scored), $result4_1_1"
echo "4.2.1.3 Ensure rsyslog default file permissions configured (Scored), $result4_2_1_3"
echo "4.2.1.4 Ensure rsyslog is configured to send logs to a remote log host (Scored), $result4_2_1_4"
echo "4.2.1.5 Ensure remote rsyslog messages are only accepted on designated log hosts (Not Scored), $result4_2_1_5"
echo "4.2.2.1 Ensure syslog-ng service is enabled (Scored), $result4_2_2_1"
echo "4.2.2.3 Ensure syslog-ng default file permissions configured (Scored), $result4_2_2_3"
echo "4.2.2.5 Ensure remote syslog-ng messages are only accepted on designated log hosts (Not Scored), $result4_2_2_5"
echo "4.2.3 Ensure rsyslog or syslog-ng is installed (Scored), $result4_2_3"
echo "4.2.4 Ensure permissions on all logfiles are configured (Scored), $result4_2_4"