echo "5.1.1, Ensure cron daemon is enabled (Scored), $result5_1_1"
echo "5.1.2, Ensure permissions on /etc/crontab are configured (Scored), $result5_1_2"
echo "5.1.3, Ensure permissions on /etc/cron.hourly are configured (Scored), $result5_1_3"
echo "5.1.4, Ensure permissions on /etc/cron.daily are configured (Scored), $result5_1_4"
echo "5.1.5, Ensure permissions on /etc/cron.weekly are configured (Scored), $result5_1_5"
echo "5.1.6, Ensure permissions on /etc/cron.monthly are configured (Scored), $result5_1_6"
echo "5.1.7, Ensure permissions on /etc/cron.d are configured (Scored), $result5_1_7"
echo "5.1.8, Ensure at/cron is restricted to authorized users (Scored), $result5_1_8"
echo "5.2.1, Ensure permissions on /etc/ssh/sshd_config are configured (Scored), $result5_2_1"
echo "5.2.2, Ensure SSH Protocol is set to 2 (Scored), $result5_2_2"
echo "5.2.3, Ensure SSH LogLevel is set to INFO (Scored), $result5_2_3"
echo "5.2.4, Ensure SSH X11 forwarding is disabled (Scored), $result5_2_4"
echo "5.2.5, Ensure SSH MaxAuthTries is set to 4 or less (Scored), $result5_2_5"
echo "5.2.6, Ensure SSH IgnoreRhosts is enabled (Scored), $result5_2_6"
echo "5.2.7, Ensure SSH HostbasedAuthentication is disabled (Scored), $result5_2_7"
echo "5.2.8, Ensure SSH root login is disabled (Scored), $result5_2_8"
echo "5.2.9, Ensure SSH PermitEmptyPasswords is disabled (Scored), $result5_2_9"
echo "5.2.10, Ensure SSH PermitUserEnvironment is disabled (Scored), $result5_2_10"
echo "5.2.11, Ensure only approved ciphers are used (Scored), $result5_2_11"
echo "5.2.12, Ensure only approved MAC algorithms are used (Scored), $result5_2_12"
echo "5.2.13, Ensure SSH Idle Timeout Interval is configured (Scored), $result5_2_13"
echo "5.2.14, Ensure SSH LoginGraceTime is set to one minute or less (Scored), $result5_2_14"
echo "5.2.15, Ensure SSH access is limited (Scored), $result5_2_15"
echo "5.2.16, Ensure SSH warning banner is configured (Scored), $result5_2_16"
echo "5.3.1, Ensure password creation requirements are configured (Scored), $result5_3_1"
echo "5.3.3, Ensure password reuse is limited (Scored), $result5_3_3"
echo "5.3.4, Ensure password hashing algorithm is SHA-512 (Scored), $result5_3_4"
echo "5.4.1.1, Ensure password expiration is 90 days or less (Scored), $result5_4_1_1"
echo "5.4.1.2, Ensure minimum days between password changes is 7 or more (Scored), $result5_4_1_2"
echo "5.4.1.3, Ensure password expiration warning days is 7 or more (Scored), $result5_4_1_3"
echo "5.4.1.4, Ensure inactive password lock is 30 days or less (Scored), $result5_4_1_4"
echo "5.4.2, Ensure system accounts are non-login (Scored), $result5_4_2"
echo "5.4.3, Ensure default group for the root account is GID 0 (Scored), $result5_4_3"
echo "5.4.4, Ensure default user umask is 027 or more restrictive (Scored), $result5_4_4"